// automatically generated by the FlatBuffers compiler, do not modify

package wifikeycontrol

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ControlSwitchEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ControlSwitchEvent {
        __init(_i, _bb)
        return this
    }
    val edge : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsControlSwitchEvent(_bb: ByteBuffer): ControlSwitchEvent = getRootAsControlSwitchEvent(_bb, ControlSwitchEvent())
        fun getRootAsControlSwitchEvent(_bb: ByteBuffer, obj: ControlSwitchEvent): ControlSwitchEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createControlSwitchEvent(builder: FlatBufferBuilder, edge: Byte) : Int {
            builder.startTable(1)
            addEdge(builder, edge)
            return endControlSwitchEvent(builder)
        }
        fun startControlSwitchEvent(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addEdge(builder: FlatBufferBuilder, edge: Byte) = builder.addByte(0, edge, 0)
        fun endControlSwitchEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
