// automatically generated by the FlatBuffers compiler, do not modify

package wifikeycontrol

@Suppress("unused")
class Edge private constructor() {
    companion object {
        const val None: Byte = 0
        const val Left: Byte = 1
        const val Right: Byte = 2
        const val Top: Byte = 3
        const val Bottom: Byte = 4
        const val Hotkey: Byte = 5
        const val ReturnToPC: Byte = 6
    }
}
