// automatically generated by the FlatBuffers compiler, do not modify

package wifikeycontrol

@Suppress("unused")
class EventType private constructor() {
    companion object {
        const val None: Byte = 0
        const val MouseMoveRel: Byte = 1
        const val MouseClick: Byte = 2
        const val MouseScroll: Byte = 3
        const val KeyPress: Byte = 4
        const val KeyRelease: Byte = 5
        const val ControlSwitch: Byte = 6
        const val Heartbeat: Byte = 7
        const val HeartbeatAck: Byte = 8
    }
}
