// automatically generated by the FlatBuffers compiler, do not modify

package wifikeycontrol

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class InputEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : InputEvent {
        __init(_i, _bb)
        return this
    }
    val type : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val timestamp : ULong
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val mouseMove : wifikeycontrol.MouseMoveEvent? get() = mouseMove(wifikeycontrol.MouseMoveEvent())
    fun mouseMove(obj: wifikeycontrol.MouseMoveEvent) : wifikeycontrol.MouseMoveEvent? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val mouseClick : wifikeycontrol.MouseClickEvent? get() = mouseClick(wifikeycontrol.MouseClickEvent())
    fun mouseClick(obj: wifikeycontrol.MouseClickEvent) : wifikeycontrol.MouseClickEvent? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val mouseScroll : wifikeycontrol.MouseScrollEvent? get() = mouseScroll(wifikeycontrol.MouseScrollEvent())
    fun mouseScroll(obj: wifikeycontrol.MouseScrollEvent) : wifikeycontrol.MouseScrollEvent? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val key : wifikeycontrol.KeyEvent? get() = key(wifikeycontrol.KeyEvent())
    fun key(obj: wifikeycontrol.KeyEvent) : wifikeycontrol.KeyEvent? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val controlSwitch : wifikeycontrol.ControlSwitchEvent? get() = controlSwitch(wifikeycontrol.ControlSwitchEvent())
    fun controlSwitch(obj: wifikeycontrol.ControlSwitchEvent) : wifikeycontrol.ControlSwitchEvent? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsInputEvent(_bb: ByteBuffer): InputEvent = getRootAsInputEvent(_bb, InputEvent())
        fun getRootAsInputEvent(_bb: ByteBuffer, obj: InputEvent): InputEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createInputEvent(builder: FlatBufferBuilder, type: Byte, timestamp: ULong, mouseMoveOffset: Int, mouseClickOffset: Int, mouseScrollOffset: Int, keyOffset: Int, controlSwitchOffset: Int) : Int {
            builder.startTable(7)
            addTimestamp(builder, timestamp)
            addControlSwitch(builder, controlSwitchOffset)
            addKey(builder, keyOffset)
            addMouseScroll(builder, mouseScrollOffset)
            addMouseClick(builder, mouseClickOffset)
            addMouseMove(builder, mouseMoveOffset)
            addType(builder, type)
            return endInputEvent(builder)
        }
        fun startInputEvent(builder: FlatBufferBuilder) = builder.startTable(7)
        fun addType(builder: FlatBufferBuilder, type: Byte) = builder.addByte(0, type, 0)
        fun addTimestamp(builder: FlatBufferBuilder, timestamp: ULong) = builder.addLong(1, timestamp.toLong(), 0)
        fun addMouseMove(builder: FlatBufferBuilder, mouseMove: Int) = builder.addOffset(2, mouseMove, 0)
        fun addMouseClick(builder: FlatBufferBuilder, mouseClick: Int) = builder.addOffset(3, mouseClick, 0)
        fun addMouseScroll(builder: FlatBufferBuilder, mouseScroll: Int) = builder.addOffset(4, mouseScroll, 0)
        fun addKey(builder: FlatBufferBuilder, key: Int) = builder.addOffset(5, key, 0)
        fun addControlSwitch(builder: FlatBufferBuilder, controlSwitch: Int) = builder.addOffset(6, controlSwitch, 0)
        fun endInputEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishInputEventBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedInputEventBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
