// automatically generated by the FlatBuffers compiler, do not modify

package wifikeycontrol

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class KeyEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : KeyEvent {
        __init(_i, _bb)
        return this
    }
    val keycode : Int
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val key : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val keyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun keyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val modifiers : UByte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsKeyEvent(_bb: ByteBuffer): KeyEvent = getRootAsKeyEvent(_bb, KeyEvent())
        fun getRootAsKeyEvent(_bb: ByteBuffer, obj: KeyEvent): KeyEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createKeyEvent(builder: FlatBufferBuilder, keycode: Int, keyOffset: Int, modifiers: UByte) : Int {
            builder.startTable(3)
            addKey(builder, keyOffset)
            addKeycode(builder, keycode)
            addModifiers(builder, modifiers)
            return endKeyEvent(builder)
        }
        fun startKeyEvent(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addKeycode(builder: FlatBufferBuilder, keycode: Int) = builder.addInt(0, keycode, 0)
        fun addKey(builder: FlatBufferBuilder, key: Int) = builder.addOffset(1, key, 0)
        fun addModifiers(builder: FlatBufferBuilder, modifiers: UByte) = builder.addByte(2, modifiers.toByte(), 0)
        fun endKeyEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
