// automatically generated by the FlatBuffers compiler, do not modify

package wifikeycontrol

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MouseScrollEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MouseScrollEvent {
        __init(_i, _bb)
        return this
    }
    val dx : Short
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos) else 0
        }
    val dy : Short
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMouseScrollEvent(_bb: ByteBuffer): MouseScrollEvent = getRootAsMouseScrollEvent(_bb, MouseScrollEvent())
        fun getRootAsMouseScrollEvent(_bb: ByteBuffer, obj: MouseScrollEvent): MouseScrollEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMouseScrollEvent(builder: FlatBufferBuilder, dx: Short, dy: Short) : Int {
            builder.startTable(2)
            addDy(builder, dy)
            addDx(builder, dx)
            return endMouseScrollEvent(builder)
        }
        fun startMouseScrollEvent(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addDx(builder: FlatBufferBuilder, dx: Short) = builder.addShort(0, dx, 0)
        fun addDy(builder: FlatBufferBuilder, dy: Short) = builder.addShort(1, dy, 0)
        fun endMouseScrollEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
