// automatically generated by the FlatBuffers compiler, do not modify

package wifikeycontrol

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MouseClickEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MouseClickEvent {
        __init(_i, _bb)
        return this
    }
    val button : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val pressed : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMouseClickEvent(_bb: ByteBuffer): MouseClickEvent = getRootAsMouseClickEvent(_bb, MouseClickEvent())
        fun getRootAsMouseClickEvent(_bb: ByteBuffer, obj: MouseClickEvent): MouseClickEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMouseClickEvent(builder: FlatBufferBuilder, button: Byte, pressed: Boolean) : Int {
            builder.startTable(2)
            addPressed(builder, pressed)
            addButton(builder, button)
            return endMouseClickEvent(builder)
        }
        fun startMouseClickEvent(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addButton(builder: FlatBufferBuilder, button: Byte) = builder.addByte(0, button, 0)
        fun addPressed(builder: FlatBufferBuilder, pressed: Boolean) = builder.addBoolean(1, pressed, false)
        fun endMouseClickEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
