// automatically generated by the FlatBuffers compiler, do not modify

package wifikeycontrol

@Suppress("unused")
class MouseButton private constructor() {
    companion object {
        const val None: Byte = 0
        const val Left: Byte = 1
        const val Right: Byte = 2
        const val Middle: Byte = 3
        const val X1: Byte = 4
        const val X2: Byte = 5
    }
}
