// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wifikeycontrol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ControlSwitchEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsControlSwitchEvent(buf []byte, offset flatbuffers.UOffsetT) *ControlSwitchEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ControlSwitchEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishControlSwitchEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsControlSwitchEvent(buf []byte, offset flatbuffers.UOffsetT) *ControlSwitchEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ControlSwitchEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedControlSwitchEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ControlSwitchEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ControlSwitchEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ControlSwitchEvent) Edge() Edge {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Edge(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ControlSwitchEvent) MutateEdge(n Edge) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func ControlSwitchEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ControlSwitchEventAddEdge(builder *flatbuffers.Builder, edge Edge) {
	builder.PrependInt8Slot(0, int8(edge), 0)
}
func ControlSwitchEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
