// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wifikeycontrol

import "strconv"

type Edge int8

const (
	EdgeNone       Edge = 0
	EdgeLeft       Edge = 1
	EdgeRight      Edge = 2
	EdgeTop        Edge = 3
	EdgeBottom     Edge = 4
	EdgeHotkey     Edge = 5
	EdgeReturnToPC Edge = 6
)

var EnumNamesEdge = map[Edge]string{
	EdgeNone:       "None",
	EdgeLeft:       "Left",
	EdgeRight:      "Right",
	EdgeTop:        "Top",
	EdgeBottom:     "Bottom",
	EdgeHotkey:     "Hotkey",
	EdgeReturnToPC: "ReturnToPC",
}

var EnumValuesEdge = map[string]Edge{
	"None":       EdgeNone,
	"Left":       EdgeLeft,
	"Right":      EdgeRight,
	"Top":        EdgeTop,
	"Bottom":     EdgeBottom,
	"Hotkey":     EdgeHotkey,
	"ReturnToPC": EdgeReturnToPC,
}

func (v Edge) String() string {
	if s, ok := EnumNamesEdge[v]; ok {
		return s
	}
	return "Edge(" + strconv.FormatInt(int64(v), 10) + ")"
}
