// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wifikeycontrol

import "strconv"

type EventType int8

const (
	EventTypeNone          EventType = 0
	EventTypeMouseMoveRel  EventType = 1
	EventTypeMouseClick    EventType = 2
	EventTypeMouseScroll   EventType = 3
	EventTypeKeyPress      EventType = 4
	EventTypeKeyRelease    EventType = 5
	EventTypeControlSwitch EventType = 6
	EventTypeHeartbeat     EventType = 7
	EventTypeHeartbeatAck  EventType = 8
)

var EnumNamesEventType = map[EventType]string{
	EventTypeNone:          "None",
	EventTypeMouseMoveRel:  "MouseMoveRel",
	EventTypeMouseClick:    "MouseClick",
	EventTypeMouseScroll:   "MouseScroll",
	EventTypeKeyPress:      "KeyPress",
	EventTypeKeyRelease:    "KeyRelease",
	EventTypeControlSwitch: "ControlSwitch",
	EventTypeHeartbeat:     "Heartbeat",
	EventTypeHeartbeatAck:  "HeartbeatAck",
}

var EnumValuesEventType = map[string]EventType{
	"None":          EventTypeNone,
	"MouseMoveRel":  EventTypeMouseMoveRel,
	"MouseClick":    EventTypeMouseClick,
	"MouseScroll":   EventTypeMouseScroll,
	"KeyPress":      EventTypeKeyPress,
	"KeyRelease":    EventTypeKeyRelease,
	"ControlSwitch": EventTypeControlSwitch,
	"Heartbeat":     EventTypeHeartbeat,
	"HeartbeatAck":  EventTypeHeartbeatAck,
}

func (v EventType) String() string {
	if s, ok := EnumNamesEventType[v]; ok {
		return s
	}
	return "EventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
