// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wifikeycontrol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InputEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsInputEvent(buf []byte, offset flatbuffers.UOffsetT) *InputEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InputEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishInputEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInputEvent(buf []byte, offset flatbuffers.UOffsetT) *InputEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InputEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInputEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InputEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InputEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InputEvent) Type() EventType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return EventType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *InputEvent) MutateType(n EventType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *InputEvent) Timestamp() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InputEvent) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *InputEvent) MouseMove(obj *MouseMoveEvent) *MouseMoveEvent {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MouseMoveEvent)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *InputEvent) MouseClick(obj *MouseClickEvent) *MouseClickEvent {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MouseClickEvent)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *InputEvent) MouseScroll(obj *MouseScrollEvent) *MouseScrollEvent {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MouseScrollEvent)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *InputEvent) Key(obj *KeyEvent) *KeyEvent {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(KeyEvent)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *InputEvent) ControlSwitch(obj *ControlSwitchEvent) *ControlSwitchEvent {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ControlSwitchEvent)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func InputEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func InputEventAddType(builder *flatbuffers.Builder, type_ EventType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func InputEventAddTimestamp(builder *flatbuffers.Builder, timestamp uint64) {
	builder.PrependUint64Slot(1, timestamp, 0)
}
func InputEventAddMouseMove(builder *flatbuffers.Builder, mouseMove flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(mouseMove), 0)
}
func InputEventAddMouseClick(builder *flatbuffers.Builder, mouseClick flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(mouseClick), 0)
}
func InputEventAddMouseScroll(builder *flatbuffers.Builder, mouseScroll flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(mouseScroll), 0)
}
func InputEventAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(key), 0)
}
func InputEventAddControlSwitch(builder *flatbuffers.Builder, controlSwitch flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(controlSwitch), 0)
}
func InputEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
