// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wifikeycontrol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyEvent(buf []byte, offset flatbuffers.UOffsetT) *KeyEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyEvent(buf []byte, offset flatbuffers.UOffsetT) *KeyEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyEvent) Keycode() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KeyEvent) MutateKeycode(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *KeyEvent) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyEvent) Modifiers() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KeyEvent) MutateModifiers(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func KeyEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func KeyEventAddKeycode(builder *flatbuffers.Builder, keycode int32) {
	builder.PrependInt32Slot(0, keycode, 0)
}
func KeyEventAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func KeyEventAddModifiers(builder *flatbuffers.Builder, modifiers byte) {
	builder.PrependByteSlot(2, modifiers, 0)
}
func KeyEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
