// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wifikeycontrol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MouseClickEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsMouseClickEvent(buf []byte, offset flatbuffers.UOffsetT) *MouseClickEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MouseClickEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishMouseClickEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMouseClickEvent(buf []byte, offset flatbuffers.UOffsetT) *MouseClickEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MouseClickEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMouseClickEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MouseClickEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MouseClickEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MouseClickEvent) Button() MouseButton {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return MouseButton(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MouseClickEvent) MutateButton(n MouseButton) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *MouseClickEvent) Pressed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MouseClickEvent) MutatePressed(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func MouseClickEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MouseClickEventAddButton(builder *flatbuffers.Builder, button MouseButton) {
	builder.PrependInt8Slot(0, int8(button), 0)
}
func MouseClickEventAddPressed(builder *flatbuffers.Builder, pressed bool) {
	builder.PrependBoolSlot(1, pressed, false)
}
func MouseClickEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
