// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wifikeycontrol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MouseScrollEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsMouseScrollEvent(buf []byte, offset flatbuffers.UOffsetT) *MouseScrollEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MouseScrollEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishMouseScrollEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMouseScrollEvent(buf []byte, offset flatbuffers.UOffsetT) *MouseScrollEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MouseScrollEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMouseScrollEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MouseScrollEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MouseScrollEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MouseScrollEvent) Dx() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseScrollEvent) MutateDx(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func (rcv *MouseScrollEvent) Dy() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseScrollEvent) MutateDy(n int16) bool {
	return rcv._tab.MutateInt16Slot(6, n)
}

func MouseScrollEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MouseScrollEventAddDx(builder *flatbuffers.Builder, dx int16) {
	builder.PrependInt16Slot(0, dx, 0)
}
func MouseScrollEventAddDy(builder *flatbuffers.Builder, dy int16) {
	builder.PrependInt16Slot(1, dy, 0)
}
func MouseScrollEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
