// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wifikeycontrol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MouseMoveEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsMouseMoveEvent(buf []byte, offset flatbuffers.UOffsetT) *MouseMoveEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MouseMoveEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishMouseMoveEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMouseMoveEvent(buf []byte, offset flatbuffers.UOffsetT) *MouseMoveEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MouseMoveEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMouseMoveEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MouseMoveEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MouseMoveEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MouseMoveEvent) Dx() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseMoveEvent) MutateDx(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func (rcv *MouseMoveEvent) Dy() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseMoveEvent) MutateDy(n int16) bool {
	return rcv._tab.MutateInt16Slot(6, n)
}

func MouseMoveEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MouseMoveEventAddDx(builder *flatbuffers.Builder, dx int16) {
	builder.PrependInt16Slot(0, dx, 0)
}
func MouseMoveEventAddDy(builder *flatbuffers.Builder, dy int16) {
	builder.PrependInt16Slot(1, dy, 0)
}
func MouseMoveEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
