// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function EnableUSBMode() {
  return window['go']['main']['App']['EnableUSBMode']();
}

export function GetConnectedDevice() {
  return window['go']['main']['App']['GetConnectedDevice']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function IsCapturing() {
  return window['go']['main']['App']['IsCapturing']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsControllingAndroid() {
  return window['go']['main']['App']['IsControllingAndroid']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function ReturnToPC() {
  return window['go']['main']['App']['ReturnToPC']();
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
