// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs():Promise<void>;

export function GetConnectedDevice():Promise<string>;

export function GetLogs():Promise<Array<string>>;

export function IsCapturing():Promise<boolean>;

export function IsConnected():Promise<boolean>;

export function IsControllingAndroid():Promise<boolean>;

export function IsServerRunning():Promise<boolean>;

export function ReturnToPC():Promise<void>;

export function StartCapture():Promise<void>;

export function StartServer():Promise<void>;

export function StopCapture():Promise<void>;

export function StopServer():Promise<void>;
